branches:
  only:
  - master
  - coverity_scan
language: c
compiler: gcc
dist: xenial
sudo: true
script:
  - ./prepare.sh
  - make multiboot
env:
  global:
  - secure: qaV69OQ4rAaKSU+P/I3bxhG5sUuKH7KsTiPmcfPFQK+XCi9MSPveCIAP6sK+04LpkXLVKBDcHZigQK4mnnzfSAGDkyQVKCEMgZw9gmg9uqG2qDFVMd9msytyw/gcFCqeuGOtVrQt+J+Uv1dagAGWOwo31GSGHevRt6awm00iwObQY+Un/7iPF5Ac2NgPMuRr7FUC/mMf9I2Yst+iNHANR71HgEPSzrSkB5J7Qb/Y3O0z0iDRzWnjcLsBQBkeUF95QnSljh+hxKVAoCcv7uhlZNFVDgpVndd6lbb5C19sXdIdf38S4I+r/0ZjWM3e8+gmtEOeWOrV9Jghk7rXGWFDq0Vfr8No2IAvQEHmEZ+LklcvpsX0qpMc68kfwfFevTQUFuK97m4Vpdzmtr7ZU3s9CK/oXd5L10tvIhyKQQdu8u6jwW3R7bwTJHwNmvO6JuzUpK6xQtvEpJAap1k3c93RNy5oLEooGIyFYGOdABSHKRKVOu6POGCGfMXIjrXN7II1Qw7k8lIPh6u5ESjZY0qid0azoKgHv+htKWG0h0xZepro7ZBB7TRZL3F6Cnpl1BJnRojGtCy5GV2PKgvx/T41r377VLBb21Cvq/bvjlXiN/uyhAmE5iH9VFLymd355Ordm1fTkpIhpdzvfcQWr5X+cQLfItjCJbzArLzumf1snaI=
  - secure: Am3jQ54JkwI3IsZ3ixSOP2okkFwmk2wRQbo09tHj65Cc1np4kG89zJqoH629ixg15mRJKYEXtAmh7cF8h44+ycmtngCqPNBo/iTecm+LyTQle2sG0VnuZ5kARZJJcXUDrqRLrVfI/nI8NcdmVy1MTJM0TLfpVMVf5SanSTPIy3f8Gk4suWSPmT/HvUr957Qa71RK1+YUkmGo/F22TKXmioyBBwal4c1ivpdEG/mIORX0s/NVNk1pSuClp6szfxDfoUli8eiwL8lhrU4G6Amstev5JOr0BbvvZuKwnjjNWuZOwV5rQb4okhyIpXp/e7z3pi2BqwBtw77h58BT/S2fvtkc/3hRW3jGjEGwVUZ7RgrG2yatUtp7Akn4JpZPRVSmRrNzO8um1ZnurUMRi4MyOjO85S7xiMBFqB/6RA+FixxVoXGfE0TFR55zXUXOddl5Meb04TlAM4n09F118iPZXmklq9ZdY6DpiEcfWvDmZxlk72Tsuc7Gs+jRZjcgFoPDQJUr2jW3sPvohUPFjO76MGX5t0mY5MozFBmLHOnXNcFmiYLpHsTDlFRGz2y4fOin3EY5e3+CrWfZq7S8mQUgUA0VNgmhr3UPoL96hpjWQ95RS0oKpNdU5C4gy4aJ1LhNyaTIv2Vv8Y6Ynugx6MaoCGsxh8MlYb+qS3ANjVLU+XY=
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq nasm
- sudo apt-get install -qq libisl15
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: mellowcandle/epOS
      description: Build submitted via Travis CI
    notification_email: ramon.fried@gmail.com
    build_command_prepend: cov-configure --template --comptype gcc --compiler i686-elf-gcc; make clean; ./prepare.sh
    build_command: make -j4 multiboot
    branch_pattern: coverity_scan
